version: "3"
services:
  postgres:
    container_name: loans_postgres
    image: postgres:15-alpine
    networks:
      - default
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loans
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: loans_redis
    image: redis
    networks:
      - default
    ports:
      - "6380:6379"
  node:
    container_name: loans_node
    image: node:18-alpine
    working_dir: /code/frontend/
    command: 
      - sh 
      - -c 
      - |
        npm install && npm run dev
    networks:
      - default
    ports:
      - "5173:5173"
    volumes:
      - .:/code
  django:
    container_name: loans_django
    build:
      context: ./
      dockerfile: docker/DockerfileDjango
    command: 
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
