# Generated by Django 4.2.4 on 2023-08-27 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrequestquestionresponse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-id'], 'verbose_name': 'Loan Request', 'verbose_name_plural': 'Loan Requests'},
        ),
        migrations.AlterModelOptions(
            name='loanrequestquestionresponse',
            options={'ordering': ['id'], 'verbose_name': 'Loan Request Question Response', 'verbose_name_plural': 'Loan Request Question Responses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordering'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['id'], 'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status_external',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255, verbose_name='External Status'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status_internal',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255, verbose_name='Internal Status'),
        ),
        migrations.AlterField(
            model_name='loanrequestquestionresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='apps/loans/storage/loan_request_question_response', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='loanrequestquestionresponse',
            name='question_label',
            field=models.CharField(max_length=255, verbose_name='Question Label'),
        ),
        migrations.AlterField(
            model_name='loanrequestquestionresponse',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('date', 'Date'), ('file', 'File'), ('boolean', 'Boolean')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
