# Generated by Django 4.2.4 on 2023-08-27 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestquestionresponse',
            name='question_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Question Key'),
            preserve_default=False,
        ),
    ]
